### ISSUE TITLE
Running a basic program using kafka-graphs

### ISSUE THREAD

**Issue by PKatGITHUB** [rayokota/kafka-graphs#1]
Hello
I want to run a simple program using kafka-graphs. I am using Jupyter notebok (spylon kernel). Can I get a simple know-how about how to setup the environment and use kafka-graphs. A sample executable code would be great!

**Comment by rayokota** [comment]
Please take a look at the unit tests, such as https://github.com/rayokota/kafka-graphs/blob/master/kafka-graphs-core/src/test/java/io/kgraph/GraphOperationsITCase.java.

**Comment by PKatGITHUB** [comment]
Thanks!
Will give it a shot! :D
